
ALTER TABLE public.legacy_locker
  ADD COLUMN IF NOT EXISTS life_overview text,
  ADD COLUMN IF NOT EXISTS digital_identity text,
  ADD COLUMN IF NOT EXISTS personal_philosophies text,
  ADD COLUMN IF NOT EXISTS medical_preferences text,
  ADD COLUMN IF NOT EXISTS executor_instructions text,
  ADD COLUMN IF NOT EXISTS subscriptions text,
  ADD COLUMN IF NOT EXISTS household_operations text,
  ADD COLUMN IF NOT EXISTS financial_crypto text,
  ADD COLUMN IF NOT EXISTS parenting_preferences text,
  ADD COLUMN IF NOT EXISTS emotional_behavioral text,
  ADD COLUMN IF NOT EXISTS developmental_goals text,
  ADD COLUMN IF NOT EXISTS letters_to_children text,
  ADD COLUMN IF NOT EXISTS photo_video_documentation text,
  ADD COLUMN IF NOT EXISTS physical_documents text,
  ADD COLUMN IF NOT EXISTS sentimental_items text,
  ADD COLUMN IF NOT EXISTS crypto_passwords text,
  ADD COLUMN IF NOT EXISTS property_walkthrough text,
  ADD COLUMN IF NOT EXISTS home_maintenance text,
  ADD COLUMN IF NOT EXISTS neighborhood_contacts text,
  ADD COLUMN IF NOT EXISTS rental_property text,
  ADD COLUMN IF NOT EXISTS sentimental_distribution text,
  ADD COLUMN IF NOT EXISTS legacy_messages text,
  ADD COLUMN IF NOT EXISTS charitable_giving text;
